const mongoose = require('mongoose');

const personSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
  gender: String,
  height: String,
  bodyType: String,
  phoneNumber: String,
  clientEmail: String,
  originallyFrom: String,
  seeking: String,
  ageRange: String,
  birthday: Date,
  siblings: String,
  ethnicity: String,
  partnerEthnicity: Array,
  religion: String,
  politics: String,
  children: String,
  mentalHealth: String,
  wantChildren: String,
  stepParent: String,
  alcoholUse: String,
  cigaretteUse: String,
  marijuanaUse: String,
  marijuanaTypes: Array,
  exercise: String,
  frequentSpot: String,
  celebCrush: String,
  tattoos: String,
  totalTattoos: {type: Number, default: 0},
  totalPiercings: {type: Number, default: 0},
  tattooPlaces: Array,
  partnerTattoos: String,
  piercings: String,
  piercingPlaces: Array,
  partnerPiercings: String,
  socialMedia: String,
  military: String,
  militaryBranch: String,
  partnerMilitary: String,
  livingSituation: String,
  livingStatus: String,
  areaOfTown: String,
  verafiedJoinReason: String,
  mixers: String,
  verafiedSuggestions: String,
  selfEsteem: String,
  outdoorsy: String,
  outdoorActivities: String,
  prevMarried: String,
  hobbies1: String,
  hobbies2: String,
  hobbies3: String,
  pets: String,
  petTypes: Array,
  partnerPets: String,
  books: String,
  bookTypes: Array,
  tv: String,
  tvTypes: Array,
  movies: String,
  favMovieGenre: String,
  gamer: String,
  favGameGenre: String,
  profession: String,
  professionIndustry: String,
  professionLength: String,
  professionSchedule: String,
  threePhysicalTraits: String,
  threePersonalityTraits: String,
  whatDoYouWant: String,
  dealBreakers: String,
  partnerLooks: String,
  familyCloseness: String,
  beenInLove: {type: Number, default: 0},
  heartBreaker: String,
  intimacy: String,
  whenLastRelationship: String,
  whyLastRelationship: String,
  threePersonalGoals: String,
  threeCharacterFlaws: String,
  threeThingsTable: String,
  holidays: String,
  lastBirthday: String,
  dayOff: String,
  threeSelfLove: String,
  petPeeves: String,
  threePastRelationshipIssues: String,
  idealFirstDate: String,
  communicationStyle: String,
  reliable: String,
  planner: String,
  hygiene: String,
  familyInVegas: String,
  partnerType: String,
  fiveYearPlan: String,
  dominantSubmissive: String,
  adventurer: String,
  perfectDate: String,
  cooking: String,
  likeSports: String,
  littleKnownFact: String,
  prizedPossesion: String,
  extraInfo: String,
  criminalHistory: String,
  trulyValue: String,
  likeTravel: String,
  travelledOutsideUS: String,
  travelledTo: Array,
  whatDoYouWant: String,
  loveLanguage: String,
  relationshipGoal: String,
  uploadedImages: {type: Array, default: [
    {
      "path" : "uploads/default/default-profile-one.jpeg",
  },
    {
      "path" : "uploads/default/default-profile-two.jpeg",
  },
    {
      "path" : "uploads/default/default-profile-three.jpeg",
  },
    {
      "path" : "uploads/default/default-profile-four.jpeg",
  },
    {
      "path" : "uploads/default/default-profile-five.jpeg",
  },
]}

}, {timestamps: true})

const Person = mongoose.model('Person', personSchema);

module.exports = Person;