const mongoose = require('mongoose');

const personSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
  gender: String,
  originallyFrom: String,
  seeking: String,
  ageRange: String,
  birthday: Date,
  ethnicity: String,
  religion: String,
  politics: String,
  children: String,
  mentalHealth: String,
  wantChildren: String,
  stepParent: String,
  alcoholUse: String,
  cigaretteUse: String,
  marijuanaUse: String,
  exercise: String,
  frequentSpot: String,
  celebCrush: String,
  tattoos: String,
  tattooPlaces: Array,
  partnerTattoos: String,
  piercings: String,
  piercingPlaces: Array,
  socialMedia: String,
  military: String,
  militaryBranch: String,
  partnerMilitary: String,
  livingSituation: String,
  livingStatus: String,
  areaOfTown: String,
  outdoorsy: String,
  outdoorActivities: String,
  prevMarried: String,
  prevMarriedAmount: Number,
  hobbies1: String,
  hobbies2: String,
  hobbies3: String,
  pets: String,
  petTypes: Array,
  books: String,
  bookTypes: Array,
  tv: String,
  tvTypes: Array,
  movies: String,
  favMovieGenre: String,
  gamer: String,
  favGameGenre: String,
  profession: String,
  professionLength: Number,
  professionSchedule: String,
  threePhysicalTraits: String,
  threePersonalityTraits: String,
  whatDoYouWant: String,
  dealBreakers: String,
  partnerLooks: String,
  familyCloseness: String,
  beenInLove: Number,
  heartBreaker: String,
  intimacy: String,
  whenLastRelationship: String,
  whyLastRelationship: String,
  threePersonalGoals: String,
  threeCharacterFlaws: String,
  threeThingsTable: String,
  holidays: String,
  lastBirthday: String,
  dayOff: String,
  threeSelfLove: String,
  petPeeves: String,
  threePastRelationshipIssues: String,
  idealFirstDate: String,
  communicationStyle: String,
  reliable: String,
  planner: String,
  hygiene: String,
  familyInVegas: String,
  partnerType: String,
  fiveYearPlan: String,
  dominantSubmissive: String,
  adventurer: String,
  perfectDate: String,
  cooking: String,
  likeSports: String,
  littleKnownFact: String,
  prizedPossesion: String,
  extraInfo: String,
  criminalHistory: String,
  trulyValue: String,
  likeTravel: String,
  travelledOutsideUS: String,
  travelledTo: Array,
  whatDoYouWant: String,
  loveLanguage: String,
  relationshipGoal: String,
  

}, {timestamps: true})

const Person = mongoose.model('Person', personSchema);

module.exports = Person;